version: '3.8'

services:
  dakodev-web:
    build: .
    container_name: dakodev_landing
    ports:
      - "3060:3060"
    restart: always
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
