services:
  web:
    build: .
    container_name: dakodev-web
    restart: always
    ports:
      - "3060:3060"
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - HOST=0.0.0.0
      - PORT=3060
